version: "3.7"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - /www/:/app

    networks:
      - minha-rede



networks:
   minha-rede:
     driver: bridge
